
gantt
    title Retro-Planning
    dateFormat DD-MM-YYYY
    axisFormat %d-%m
    section Article
        Fin app2d: done, a0, 01-01-2024,30d
        Correction Background/Method: active,a1, 15-02-2024, 5d
        Correction appl:a2,after a1, 15d
    section Dvpt  
        Bibliographie: active, 01-01-2024, 20-02-2024
        Align Part Filter: after a2, 300d
    section Formation
        Rédiger Thèse: f1, 19-03-2024,21-03-2024
    section Conf./Pr.
        Présentation 3 minutes: p1, 17-03-2024, 10d
        Journée des doctorants IRESNE:crit, after p1, 27-03-2024, 3d
        Presentation EC.: p3, 15-05-2024, 03-06-2024
        ECCOMAS: crit, 03-06-2024, 5d
        Café Thésard: crit, 28-06-2024, 1d
    section Manuscrit
        part. Intro:a4,after p3, 30d
        part. I: a5,after a4, 45d
        part. II: after a5, 75d
    section Admin.
        Fin de contract: crit, 01-10-2024,0.5d
        Dépôt du manuscrit: crit, 01-11-2024, 0.5d
        Fin Prolongation: crit, 31-12-2024, 0.5d


