
gantt
    title Retro-Planning
    dateFormat DD-MM-YYYY
    axisFormat %d-%m
    section Article
        Fin app2d: done, a0, 01-01-2024,30d
        Correction Background/Method: done,a1, 15-02-2024, 5d
        Correction appl:done,a2,after a1, 21d
        Révision: active, 01-05-2024, 90d
        Article 2: after a5, 160d 

    section Dvpt  
        Bibliographie: done,d1, 01-01-2024, 20-02-2024
        Align Part Filter: done, d2,after d1, 01-06-2024
        Align-EnKF: after d2, 15-07-2024

    section Formation
        Rédiger Thèse: done, f1, 19-03-2024,21-03-2024
        Pro.: done, f2, 13-06-2024,1d

    section Conf./Pr.
        Présentation 3 minutes: done, p1, 17-03-2024, 10d
        Journée des doctorants IRESNE:done, crit, after p1, 27-03-2024, 3d
        Presentation EC.: done, p3, 15-05-2024, 03-06-2024
        ECCOMAS: done, 03-06-2024, 5d
        Présentation CEA: crit, 28-06-2024, 1d
        Soutenance: crit, 01-12-2024, 31-12-2024
    section Manuscrit
        Bibliographie: active,a4, 01-03-2024, 135d
        part. I: active,a5, 01-05-2024, 09-08-2024
        part. II: after a5, 84d
    section Admin.
        Congés: done,&d1, 26-04-2024, 12-05-2024
        CSI: done,crit, 21-06-2024,2d
        Fin rédaction Part 1: crit, 09-08-2024, 3d
        Dépôt du manuscrit: crit, 01-11-2024, 0.5d
        Fin de contract: crit, 31-12-2024,0.5d


